title: Kevin's Blog
author: Kevinwochan
email: kevinwochan@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A blog of my adventures as a software/electrical engineer

# social links
github_username: Kevinwochan

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-cayman
